### ISSUE TITLE
As recyclerview child not working properly fling not working properly

### ISSUE THREAD

**Issue by anilbisht** [huxq17/SwipeCardsView#13]
As recyclerview child : Above recyclerview there is toolbar in activity with height 56dp because of toolbar,  SwipeCardView swipe is not working for initial 56dp but above 56 its fling is working.

**Comment by huxq17** [comment]
Could you please show your layout.xml about SwipeCardView?

**Comment by anilbisht** [comment]
This is my XML with ToolbarView id "tool_bar_view" with 56dp height and because of this height swipe left right is not working properly and if i remove this  view or reduce height to 0dp for "tool_bar_view" it works fine. for refrence this is video link [https://www.youtube.com/watch?v=WJv1KtJ7xQU&feature=youtu.be]

<?xml version="1.0" encoding="utf-8"?>
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:card="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="wrap_content"
    android:background="@color/accent_blue"
    android:gravity="center_horizontal"
    android:orientation="vertical"
    tools:ignore="MissingPrefix">

```
<View
    android:id="@+id/tool_bar_view"
    android:layout_width="match_parent"
    android:layout_height="56dp"
    android:background="@color/theme_color"

    ></View>

<LinearLayout
    android:id="@+id/swipeLayout"
    android:layout_width="match_parent"
    android:layout_height="wrap_content"
    android:layout_marginBottom="16dp"
    android:layout_marginTop="10dp"
    android:background="@android:color/transparent"
    android:orientation="vertical">

    <com.huxq17.example.dummy.SwipeCardsView
        android:id="@+id/swipCardsView"
        android:layout_width="match_parent"
        android:layout_height="215dp"
        android:background="@android:color/transparent"
        card:alphaOffsetStep="40"
        card:scaleOffsetStep="0.05"
        card:yOffsetStep="16dp" />

</LinearLayout>

<TextView
    android:id="@+id/tv_card_count"
    android:layout_width="match_parent"
    android:layout_height="wrap_content"
    android:layout_marginTop="4dp"
    android:gravity="center"
    android:text="2"
    android:textColor="@android:color/white"
    android:textSize="13sp"
    android:visibility="gone" />
```

</LinearLayout>

**Comment by huxq17** [comment]
SwipeCardsView seems to be covered by Toolbar，what's your layout root label, LinearLayout or RelativeLayout?

**Comment by huxq17** [comment]
Does SwipeCardsView invoke onShow method when click on the 56dp area?

**Comment by anilbisht** [comment]
Root layout is Linear and SwipecardView in not covered by toolbar, Actually swipecard is child of recyclerview at 0 position. onShow method not getting invoked when click on the 56dp area.

**Comment by anilbisht** [comment]
[SwipeCardsView-dummy.zip](https://github.com/huxq17/SwipeCardsView/files/497326/SwipeCardsView-dummy.zip)

This is the sample code for same, This may gives u the better idea for the same.
Thanks.

**Comment by huxq17** [comment]
ok

**Comment by huxq17** [comment]
private boolean isTouchTopView(MotionEvent ev) {
         ......
            int x = (int) ev.getRawX();
            int y = (int) ev.getRawY();
         ......
    }
Replace isTouchTopView method's  two lines code in SwipeCardsView, and swipe will work for initial 56dp @anilbisht

**Comment by anilbisht** [comment]
Thanks man. :+1:
