### ISSUE TITLE
加载更多数据如何使用？

### ISSUE THREAD

**Issue by evilchaos** [huxq17/SwipeCardsView#16]
比如说，我在网络上取了第一页数据，我浏览完后，再从网络上取第二页数据，那么在哪个地方写代码，使我可以浏览第二页的图片内容？或者你认为这部分的逻辑该如何实现，我看了半天，这部分不知道如何入手，求指点。

**Comment by huxq17** [comment]
譬如说你一页数据有十条，你可以在浏览第一条的时候加载第二页数据，然后浏览到第11条时再加载第三页，这样就可以在很大程度上保证用户浏览的流畅性。

**Comment by spiky-star** [comment]
我也没看到你是在哪page++的
