### ISSUE TITLE
如果滑动card下面加按钮呢

### ISSUE THREAD

**Issue by lushiyu5277** [huxq17/SwipeCardsView#17]
如果我想在滑动card下面加按钮，并且要求滑动的时候卡片能遮盖住按钮，我该怎么做呢？

**Comment by huxq17** [comment]
你在布局的时候把card放到按钮上面就可以

**Comment by lushiyu5277** [comment]
<FrameLayout
        android:layout_width="match_parent"
        android:layout_height="match_parent">

        <Button
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:text="关注" />

        <com.huxq17.swipecardsview.SwipeCardsView
            android:id="@+id/swipCardsView"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            android:background="#f3f3f3"
            djcity:alphaOffsetStep="40"
            djcity:scaleOffsetStep="0.08"
            djcity:yOffsetStep="30dp" />
    </FrameLayout>

我这么布局，关注按钮还是在card上面，而不是下面，我希望card在滑动时可以遮盖住我的按钮，可以实现吗？

**Comment by lushiyu5277** [comment]
<FrameLayout
        android:layout_width="match_parent"
        android:layout_height="match_parent">
        <Button
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:text="关注" />

        <com.huxq17.swipecardsview.SwipeCardsView
            android:id="@+id/swipCardsView"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            android:background="#f3f3f3"
            djcity:alphaOffsetStep="40"
            djcity:scaleOffsetStep="0.08"
            djcity:yOffsetStep="30dp" />

    </FrameLayout>
我这样布局，card还是在关注下面，我希望card在滑动时是可以遮盖住按钮的，这里如何设置实现呢？

**Comment by lushiyu5277** [comment]
我这样设置card还是在button下面显示，我希望滑动时card可以遮住button，应该如何设置呢？

  《FrameLayout
        android:layout_width="match_parent"
        android:layout_height="match_parent">

```
    <Button
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:text="关注" />

    <com.huxq17.swipecardsview.SwipeCardsView
        android:id="@+id/swipCardsView"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:background="#f3f3f3"
        djcity:alphaOffsetStep="40"
        djcity:scaleOffsetStep="0.08"
        djcity:yOffsetStep="30dp" />

</FrameLayout>
```

**Comment by lushiyu5277** [comment]
解决了，不用button就好了，好莫名啊
