### ISSUE TITLE
viewpager里面可以用吗？

### ISSUE THREAD

**Issue by 06304322** [huxq17/SwipeCardsView#19]
继承了BaseCardAdapter，实现了滑动监听，但是无法滑动。没有按照你的demo来写。

**Comment by huxq17** [comment]
目前得先设置滑动监听，再设置adater

**Comment by huxq17** [comment]
compile 'com.huxq17.android:SwipeCardsView:1.3.4'  这个版本已经可以了，不需要注意设置adapter和监听的顺序了。

**Comment by 06304322** [comment]
可以正常使用。感谢解答。
