### ISSUE TITLE
cardsView.notifyDatasetChanged(imageList)无效

### ISSUE THREAD

**Issue by iamsdk** [huxq17/SwipeCardsView#2]
啊是这样子的。听我细细道来：
步骤是这样的
 private ArrayList<BeautyMode> imageList = new ArrayList<>();   //1

imageList = GetList.getImageListByDocument(url);   //2，一个通过url赋值list的方法

 private void show() {                    //3
        if (adapter == null) {
            adapter = new Adapter(imageList, getContext()); //第一次肯定进入这里
            cardsView.setAdapter(adapter);
        } else {
            cardsView.notifyDatasetChanged(imageList);
        }
    }
这样，首先app是正常显示的。然后我用一个方法，重新赋值了imageList，步骤为：
 imageList.clear();   //1

 imageList = GetList.getImageListByDocument(url);   //2,一个通过url赋值list的方法

private void show() {                  //3
        if (adapter == null) {
            adapter = new Adapter(imageList, getContext());
            cardsView.setAdapter(adapter);
        } else {
            cardsView.notifyDatasetChanged(imageList);   //第二次肯定到这里
        }
    }
经过这三步，我发现页面没有刷新，经过断点，我发现在您的SwipeCardsView源码里(在第470行)
releasedViewList==0，所以return了。没有刷新界面，不知道是不是我操作不正确
/**
============以下是你的源码===================
     \* 对View重新排序
     */
    private void resetViewGroup() {
        if (releasedViewList.size() == 0) {
            if (viewList.size() != 0) {
                View topView = getTopView();
                if (topView != null) {
                    if (topView.getLeft() != initCenterViewX || topView.getTop() != initCenterViewY) {
                        topView.offsetLeftAndRight(initCenterViewX - topView.getLeft());
                        topView.offsetTopAndBottom(initCenterViewY - topView.getTop());
                    }
                }
            }
            return;
        }
        View changedView = releasedViewList.get(0);
        if (changedView.getLeft() == initCenterViewX) {
            releasedViewList.remove(0);
            return;
        }
        int viewSize = viewList.size();
        removeViewInLayout(changedView);
        addViewInLayout(changedView, 0, changedView.getLayoutParams(), true);
        requestLayout();
//            removeView(changedView);
//            addView(changedView,0);

```
    int newIndex = showingIndex + viewSize + 1;
    if (newIndex < dataList.size()) {
        bindCardData(newIndex, changedView);
    } else {
        changedView.setVisibility(View.GONE);
    }

    viewList.remove(changedView);
    viewList.add(changedView);
    releasedViewList.remove(0);

    if (showingIndex + 1 < dataList.size()) {
        showingIndex++;
    }
    if (null != mCardsSlideListener) {
        mCardsSlideListener.onShow(showingIndex);
    }
}
```

**Comment by huxq17** [comment]
是会有这个问题，notifydatasetchanged在数据增加的时候是正常的，这种情况可以先尝试重新new Adapter，

**Comment by huxq17** [comment]
等有时间我会把这个问题给解决掉

**Comment by iamsdk** [comment]
我想应该是这么解决（源码我也没看太多，可能错了）
在cardsview.notifyxxx(list)之后，重新把releasedViewList中index>0的元素赋值，这样对吗

**Comment by iamsdk** [comment]
那等你啥时候解决了，你告诉我一声，就在这个问题下回复一下就行了，3q

**Comment by huxq17** [comment]
已经解决了，最新的代码是没问题的。
