### ISSUE TITLE
关于分页的问题怎么处理呢？

### ISSUE THREAD

**Issue by spiky-star** [huxq17/SwipeCardsView#20]
关于分页的问题怎么处理呢？

**Comment by huxq17** [comment]
demo里数据就是分页加载的，你可以看看。

**Comment by huxq17** [comment]
`@Override
    public void dealDataResponse(List<ContentBean> bean, boolean success) {
        if (bean != null) {
            mList = bean;
            show();
        }
    }

    @Override
    public void dealDataLoading(List<ContentBean> beans) {
        mList.addAll(beans);
        show();
    }`
这里的就是，分页是数据分阶段加载，并不一定得是page++。
