### ISSUE TITLE
设置子 View 的 layout_margin 属性失效

### ISSUE THREAD

**Issue by kooguma** [huxq17/SwipeCardsView#25]
设置子 Item 最外层 layout  的属性如下：
```
<FrameLayout
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:layout_margin="12dp">
 //...
</FrameLayout>
```
右侧的 margin 属性没有效果，虽然有很多办法解决这个问题 =。=

感觉是在 onMeasure 中没有测量子 View 的原因。可能需要调用下 measureChildWithMargins() 方法。

**Comment by huxq17** [comment]
你试试，不用xrefreshview，还有没有问题。

**Comment by kooguma** [comment]
呃，我是单独用的 SwipeCardsView 这个 View ，没有用其它的。

**Comment by huxq17** [comment]
看错项目了

**Comment by huxq17** [comment]
单独设置marginRight有效果么

**Comment by kooguma** [comment]
单独设置marginRight没有效果，单独设置marginLeft有效果

**Comment by huxq17** [comment]
是什么效果？有demo能看看么

**Comment by kooguma** [comment]
以所给 Demo 为例，修改 card_item.xml 中 CardView 的属性如下：
```
<android.support.v7.widget.CardView 
    xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:card_view="http://schemas.android.com/apk/res-auto"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:layout_gravity="center_horizontal"
    android:layout_marginTop="100dp"
    android:layout_marginBottom="100dp"
    android:layout_marginLeft="36dp"
    android:layout_marginRight="36dp"
    android:foreground="?android:attr/selectableItemBackground"
    card_view:cardCornerRadius="8dp"
    card_view:cardElevation="3dp">
//...
</android.support.v7.widget.CardView>
```
其它地方不该动，效果如下：
![cc1e9e2e-c4be-4079-9bf5-737990d04080](https://cloud.githubusercontent.com/assets/13082276/25262162/d41b9290-2688-11e7-9fe7-2fee04a16ebe.png)
似乎只有 marginTop 有效

**Comment by huxq17** [comment]
android:layout_gravity="center_horizontal"用了横向居中的属性，你去掉试试

**Comment by huxq17** [comment]
item的位置应该是对的，如果item的大小有问题，你更新到com.huxq17.android:SwipeCardsView:1.3.5这个版本试试

**Comment by kooguma** [comment]
嗯，1.3.5 的版本中新增了 measureChildrenWithMargins 方法，问题解决～
