### ISSUE TITLE
Avoid rotating cards when stack is finished

### ISSUE THREAD

**Issue by nazar322** [huxq17/SwipeCardsView#9]
Let's say I have 5 cards and all 5 were already shown, calling slideCardOut method will make cards rotate from 3rd to 5th.  What would be nice is that after swiping out the last card from the stack no effect would take and slideCardOut method will be ignored. Thank you!

**Comment by huxq17** [comment]
Hi, It's done, try it on version 1.3.0 by calling retainLastCard method.
